Colab Link - https://colab.research.google.com/drive/1LajaeXEWF8b2P-2wpMvwHOCVNv84_ZJw#scrollTo=zndC-c6CmxEg

##Example 1 Boston Housing Dataset

In [45]:
import tensorflow as tf
import matplotlib.pyplot as plt
from tensorflow.keras.datasets import boston_housing

In [46]:
def mse(self, true, predicted):
        return tf.reduce_mean(tf.square(true-predicted))

In [47]:
def predict(self, x):
        return tf.reduce_sum(self.m * x, 1) + self.b

###Gradient Tape

In [48]:
def update(self, X, y, learning_rate):
        with tf.GradientTape(persistent=True) as g:
            loss = self.mse(y, self.predict(X))
            
        print("Loss: ", loss)

        dy_dm = g.gradient(loss, self.m)
        dy_db = g.gradient(loss, self.b)
        
        self.m.assign_sub(learning_rate * dy_dm)
        self.b.assign_sub(learning_rate * dy_db)

###Parameters

In [49]:
def train(self, X, y, learning_rate=0.01, epochs=5):
        
        if len(X.shape)==1:
            X=tf.reshape(X,[X.shape[0],1])
        
        self.m.assign([self.var]*X.shape[-1])
        
        for i in range(epochs):
            print("Epoch: ", i)
            
            self.update(X, y, learning_rate)

###Linear Classifier 

In [50]:
class SimpleLinearRegression:
    def __init__(self, initializer='random'):
        if initializer=='ones':
            self.var = 1.
        elif initializer=='zeros':
            self.var = 0.
        elif initializer=='random':
            selfx.var = tf.random.uniform(shape=[], minval=0., maxval=1.)
            
        self.m = tf.Variable(1., shape=tf.TensorShape(None))
        self.b = tf.Variable(self.var)
        
    def predict(self, x):
        return tf.reduce_sum(self.m * x, 1) + self.b
    
    def mse(self, true, predicted):
        return tf.reduce_mean(tf.square(true-predicted))
    
    def update(self, X, y, learning_rate):
        with tf.GradientTape(persistent=True) as g:
            loss = self.mse(y, self.predict(X))
            
        print("Loss: ", loss)

        dy_dm = g.gradient(loss, self.m)
        dy_db = g.gradient(loss, self.b)
        
        self.m.assign_sub(learning_rate * dy_dm)
        self.b.assign_sub(learning_rate * dy_db)
    
    def train(self, X, y, learning_rate=0.01, epochs=5):
        
        if len(X.shape)==1:
            X=tf.reshape(X,[X.shape[0],1])
        
        self.m.assign([self.var]*X.shape[-1])
        
        for i in range(epochs):
            print("Epoch: ", i)
            
            self.update(X, y, learning_rate)

In [51]:
(x_train, y_train), (x_test, y_test) = boston_housing.load_data()

In [52]:
mean_label = y_train.mean(axis=0)
std_label = y_train.std(axis=0)
mean_feat = x_train.mean(axis=0)
std_feat = x_train.std(axis=0)
x_train = (x_train-mean_feat)/std_feat
y_train = (y_train-mean_label)/std_label

###model

In [53]:
linear_model = SimpleLinearRegression('zeros')
linear_model.train(x_train, y_train, learning_rate=0.1, epochs=50)

Epoch:  0
Loss:  Tensor("Mean_50:0", shape=(), dtype=float32)
Epoch:  1
Loss:  Tensor("Mean_51:0", shape=(), dtype=float32)
Epoch:  2
Loss:  Tensor("Mean_52:0", shape=(), dtype=float32)
Epoch:  3
Loss:  Tensor("Mean_53:0", shape=(), dtype=float32)
Epoch:  4
Loss:  Tensor("Mean_54:0", shape=(), dtype=float32)
Epoch:  5
Loss:  Tensor("Mean_55:0", shape=(), dtype=float32)
Epoch:  6
Loss:  Tensor("Mean_56:0", shape=(), dtype=float32)
Epoch:  7
Loss:  Tensor("Mean_57:0", shape=(), dtype=float32)
Epoch:  8
Loss:  Tensor("Mean_58:0", shape=(), dtype=float32)
Epoch:  9
Loss:  Tensor("Mean_59:0", shape=(), dtype=float32)
Epoch:  10
Loss:  Tensor("Mean_60:0", shape=(), dtype=float32)
Epoch:  11
Loss:  Tensor("Mean_61:0", shape=(), dtype=float32)
Epoch:  12
Loss:  Tensor("Mean_62:0", shape=(), dtype=float32)
Epoch:  13
Loss:  Tensor("Mean_63:0", shape=(), dtype=float32)
Epoch:  14
Loss:  Tensor("Mean_64:0", shape=(), dtype=float32)
Epoch:  15
Loss:  Tensor("Mean_65:0", shape=(), dtype=float32)
Ep

###standardization  and Model Prediction 


In [54]:
x_test = (x_test-mean_feat)/std_feat
# reverse standardization
pred = linear_model.predict(x_test)
print(pred)
for i in range(len(x_test)):
	print("X=%s, Predicted=%s" % (x_test[i], y_test[i]))

Tensor("add_507:0", dtype=float32)
X=[ 1.55369355 -0.48361547  1.0283258  -0.25683275  1.03838067  0.23545815
  1.11048828 -0.93976936  1.67588577  1.5652875   0.78447637 -3.48459553
  2.25092074], Predicted=7.2
X=[-0.39242675 -0.48361547 -0.16087773 -0.25683275 -0.08840061 -0.49947436
  0.85606329 -0.68396235 -0.39603557  0.15707841 -0.30759583  0.42733126
  0.47880119], Predicted=18.8
X=[-0.39982927 -0.48361547 -0.86940196 -0.25683275 -0.3615597  -0.39790979
 -0.84607575  0.52864277 -0.51114231 -1.094663    0.78447637  0.44807713
 -0.41415936], Predicted=19.0
X=[-0.26780504 -0.48361547  1.24588095  3.89358447  0.40670026 -0.02409575
  0.84531294 -0.95767141 -0.51114231 -0.01744323 -1.71818909 -0.1687668
 -0.99934525], Predicted=27.0
X=[-0.39803715 -0.48361547 -0.97229967 -0.25683275 -0.92495034 -0.2060656
 -0.43756238  0.00361454 -0.74135579 -0.95624928  0.01092523  0.42945904
 -0.59357956], Predicted=22.2
X=[-0.3754937  -0.48361547 -0.20791668 -0.25683275  0.23597582 -0.48113631
 -0

## Linear Classifier Example 2

In [2]:
import tensorflow as tf
print(tf.__version__)

2.0.0


In [1]:
import numpy as np
import tensorflow as tf
rng = np.random
import matplotlib.pyplot as plt
%matplotlib inline

###Data

In [2]:
#Input array
X_data=np.array([[1.0, 0.0, 1.0, 0.0],[1.0, 0.0, 1.0, 1.0],[0.0, 1.0, 0.0, 1.0]])
#Output
y_data=np.array([[1.0],[1.0],[0.0]])

###Variable initialization


In [3]:
epoch=5000
lr=0.1 #learning rate

In [4]:
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior() 

Instructions for updating:
non-resource variables are not supported in the long term


### Tensorflow Graph Input


In [5]:
X = tf.placeholder(shape=[4, None], dtype= tf.float64)
Y = tf.placeholder(shape=[1, None], dtype= tf.float64)

### Set model hidden layer weights and bias


In [6]:
W_h = tf.Variable(rng.randn(3, 4), name="weight1")
b_h = tf.Variable(rng.randn(3, 1), name="bias1")

### Set model output layer weights and bias


In [7]:

W_o = tf.Variable(rng.randn(1, 3), name="weight2")
b_o = tf.Variable(rng.randn(1, 1), name="bias2")

### Linear model


In [8]:
h = tf.nn.sigmoid(tf.add(tf.matmul(W_h, X), b_h))
pred = tf.nn.sigmoid(tf.add(tf.matmul(W_o, h), b_o))

###Gradient

In [9]:
# with tf.GradientTape() as t:
#     t.watch([W_h])
E = tf.reduce_sum(tf.pow(pred - Y, 2))

dE_dW_h = tf.gradients(E, [W_h])[0]
dE_db_h = tf.gradients(E, [b_h])[0]
dE_dW_o = tf.gradients(E, [W_o])[0]
dE_db_o = tf.gradients(E, [b_o])[0]

###model with Numpy

In [10]:
def sigmoid(x):
    return 1 / (1 + np.exp(-x))


with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    W_h_i = np.random.randn(3, 4)
    b_h_i = np.random.randn(3, 1)
    W_o_i = np.random.randn(1, 3)
    b_o_i = np.random.randn(1, 1)
    for i in range(2000):

        # Feed_Backward
        evaluated_dE_dW_h = sess.run(dE_dW_h,
                                     feed_dict={W_h: W_h_i, b_h: b_h_i, W_o: W_o_i, b_o: b_o_i, X: X_data.T, Y: y_data.T})
        W_h_i = W_h_i - 0.1 * evaluated_dE_dW_h
        evaluated_dE_db_h = sess.run(dE_db_h,
                                     feed_dict={W_h: W_h_i, b_h: b_h_i, W_o: W_o_i, b_o: b_o_i, X: X_data.T, Y: y_data.T})
        b_h_i = b_h_i - 0.1 * evaluated_dE_db_h
        evaluated_dE_dW_o = sess.run(dE_dW_o,
                                     feed_dict={W_h: W_h_i, b_h: b_h_i, W_o: W_o_i, b_o: b_o_i, X: X_data.T, Y: y_data.T})
        W_o_i = W_o_i - 0.1 * evaluated_dE_dW_o
        evaluated_dE_db_o = sess.run(dE_db_o,
                                     feed_dict={W_h: W_h_i, b_h: b_h_i, W_o: W_o_i, b_o: b_o_i, X: X_data.T, Y: y_data.T})
        b_o_i = b_o_i - 0.1 * evaluated_dE_db_o

print(W_h_i)


[[-2.29539356  3.3335849  -1.16467403  0.86555399]
 [-0.60685304  2.39649683 -0.7038883  -0.19845462]
 [-1.27287904  1.34638334 -0.82825603 -1.97611197]]


###model Prediction and Time per Epoch

In [12]:
import time

t0 = time.time()
for i in range(3):
    hidden_layer_input1 = np.dot(W_h_i, X_data[i])
    hidden_layer_input = hidden_layer_input1 + b_h_i
    hidden_layer_activations = sigmoid(hidden_layer_input)
    output_layer_input1 = np.dot(W_o_i, hidden_layer_activations)
    output_layer_input = output_layer_input1 + b_o_i
    output = sigmoid(output_layer_input)
    print(output)
t_end = time.time() - t0
print('Time per epoch: %.3f s' % (t_end / 20,))

[[0.96390224 0.93683621 0.9546137 ]]
[[0.95964222 0.94306237 0.96526293]]
[[0.05500566 0.15073976 0.89715026]]
Time per epoch: 0.000 s
